### ISSUE TITLE
freeze of build with Grep Console installed

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#166]

**Comment by anb0s** [comment]
same happens with 0.10.1

**Comment by anb0s** [comment]
After analysing the freeze with jstack, it looks like related to installed plugin GrepConsole. The main thread in RUNNABLE but always at the same code "name.schedenig.eclipse.grepconsole.adapters.TextFilter.clearStatistics(TextFilter.java:318)" where Eclox "at eclox.ui.console.ConsolePage.clear(ConsolePage.java:169)" tries to clear the console:
...
"main" prio=6 tid=0x000000000259f800 nid=0x41f4 runnable [0x000000000012e000]
   java.lang.Thread.State: RUNNABLE
    at java.util.HashMap.newValueIterator(Unknown Source)
    at java.util.HashMap$Values.iterator(Unknown Source)
    at name.schedenig.eclipse.grepconsole.adapters.TextFilter.clearStatistics(TextFilter.java:318)
    at name.schedenig.eclipse.grepconsole.adapters.TextFilter.refresh(TextFilter.java:257)
    at name.schedenig.eclipse.grepconsole.adapters.TextFilter.textSet(TextFilter.java:959)
    at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:80)
    at org.eclipse.swt.custom.DefaultContent.sendTextEvent(DefaultContent.java:796)
    at org.eclipse.swt.custom.DefaultContent.setText(DefaultContent.java:815)
    at org.eclipse.swt.custom.StyledText.setText(StyledText.java:10079)
    at eclox.ui.console.ConsolePage.clear(ConsolePage.java:169)
    at eclox.ui.console.ConsolePage.access$0(ConsolePage.java:166)
    at eclox.ui.console.ConsolePage$MyBuildJobListener$1.run(ConsolePage.java:60)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
...

**Comment by anb0s** [comment]
uninstalled the GrepConsole and it works now, but to be investigated if Eclox is the root of the bug...

**Comment by reneparis** [comment]
Just had the same issue and found a solution (for now):
As soon as i deactivate "Show in Grep View" it works for me. Just highlightning the actual console works.

**Comment by anb0s** [comment]
Thanks! Where is this "Show in Grep View" setting? I'm just cannot find it...

**Comment by reneparis** [comment]
Go to Window => Preferences => Grep Console 
In the Expressions Tab you see all items with their behaviours as symbols next to it (can be toggled).
From left to right: Style in console, Show in Grep View, Show in Statistics View, and Notification

You can also get these settings if you edit or doubleclick an expression and browse to the general tab (should be the default tab).

Did that help?

**Comment by anb0s** [comment]
Yes it did help :) Thanks!

I wrote an email to the developer of Grep Console to support me fixing it. So this request stays opened until it's fixed in Grep, Console or in Eclox...

**Comment by anb0s** [comment]
We have a workaround here and the Grep Console plugin has the issue here, it may be fixed with new version of Grep Console.
