### ISSUE TITLE
[v0.11] endRule without matching beginRule

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#174]
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -data file:/C:/Users/kenobi/eclipse-workspace/

org.eclipse.core.jobs
Error
Wed Jan 18 23:44:26 CET 2017
An internal error occurred during: "Doxygen Build [doxygen -b \eclox.ui\doc\eclox.ui.doxyfile]".

java.lang.IllegalArgumentException: endRule without matching beginRule: L/eclox.ui/doc/eclox.ui.doxyfile
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.jobs.ImplicitJobs.end(ImplicitJobs.java:114)
	at org.eclipse.core.internal.jobs.JobManager.endRule(JobManager.java:706)
	at eclox.core.doxygen.BuildJob.run(BuildJob.java:488)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by anb0s** [comment]
fixed with #177
