### ISSUE TITLE
exception after build if OUTPUT_DIRECTORY is an absolute path

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#191]
java.lang.NullPointerException
	at eclox.core.doxyfiles.Doxyfile.getOutputContainer(Doxyfile.java:232)
	at eclox.core.doxygen.BuildJob.run(BuildJob.java:470)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by anb0s** [comment]
fixed

**Comment by anb0s** [comment]
related to #190
