### ISSUE TITLE
terminate build is not working like expected

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#196]
"Terminate Build" does not stop the build and an exception is shown at the end of the build:

> java.lang.IllegalArgumentException: endRule without matching beginRule: L/eclox/eclox.ui/doc/eclox.ui.doxyfile
> 	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
> 	at org.eclipse.core.internal.jobs.ImplicitJobs.end(ImplicitJobs.java:114)
> 	at org.eclipse.core.internal.jobs.JobManager.endRule(JobManager.java:707)
> 	at eclox.core.doxygen.BuildJob.run(BuildJob.java:496)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
>

**Comment by anb0s** [comment]
done for 0.12.0
