### ISSUE TITLE
remove from history if "eclox.core.doxygen.RunException: Missing or bad doxyfile"

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#203]
The file is gone but the entry is still in eclox history and cannot be removed. May be just ask user if he wants to remove the entry in case of this exception appears. related to #199

```
org.gna.eclox.core
Error
Wed Jul 05 21:58:51 CEST 2017
Missing or bad doxyfile

eclox.core.doxygen.RunException: Missing or bad doxyfile
	at eclox.core.doxygen.Doxygen.build(Doxygen.java:221)
	at eclox.core.doxygen.BuildJob.run(BuildJob.java:433)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)


```

**Comment by anb0s** [comment]
Now with #199 the entry can be removed with new "Clear History" dialog.

**Comment by anb0s** [comment]
done
