### ISSUE TITLE
Doxyfile Editor does not work with Version 0.6.1 on Eclipse 3.2.2

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#65]
Original Savannah ticket 8844 reported by gbrocker on Tue Apr 03 15:51:55 2007.

Hi,

When I try to edit a doxyfile with Eclipse 3.2.2 and CDT 3.1.2 I always receive the error message:
&quot;Unable to create this part due to an internal error. Reason for the failure: An unexpected exception was thrown.&quot;

My doxyfile is attached to this submission.

best regards,

Jonathan

PS:
Detailed Error Message:
&quot;java.lang.NullPointerException
    at eclox.ui.editor.basic.DiagramsPart$MyEditorListener.editorChanged(DiagramsPart.java:49)
    at eclox.ui.editor.editors.AbstractEditor.fireEditorChanged(AbstractEditor.java:61)
    at eclox.ui.editor.basic.MultiEditor.refresh(MultiEditor.java:222)
    at eclox.ui.editor.basic.RadioMultiEditor.refresh(RadioMultiEditor.java:101)
    at eclox.ui.editor.basic.Part.refresh(Part.java:245)
    at org.eclipse.ui.forms.ManagedForm.doRefresh(ManagedForm.java:204)
    at org.eclipse.ui.forms.ManagedForm.refresh(ManagedForm.java:189)
    at org.eclipse.ui.forms.editor.FormPage.setActive(FormPage.java:124)
    at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:477)
    at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:596)
    at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:280)
    at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:596)
    at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:372)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:566)
    at org.eclipse.ui.internal.EditorReference.getEditor(EditorReference.java:214)
    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditorBatched(WorkbenchPage.java:2595)
    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:2528)
    at org.eclipse.ui.internal.WorkbenchPage.access$10(WorkbenchPage.java:2520)
    at org.eclipse.ui.internal.WorkbenchPage$9.run(WorkbenchPage.java:2505)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2500)
    at org.eclipse.ui.actions.OpenWithMenu.openEditor(OpenWithMenu.java:288)
    at org.eclipse.ui.actions.OpenWithMenu.access$0(OpenWithMenu.java:280)
    at org.eclipse.ui.actions.OpenWithMenu$2.handleEvent(OpenWithMenu.java:184)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:928)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3348)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2968)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:1930)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:1894)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:422)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.IDEApplication.run(IDEApplication.java:95)
    at org.eclipse.core.internal.runtime.PlatformActivator$1.run(PlatformActivator.java:78)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:92)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:68)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.core.launcher.Main.invokeFramework(Main.java:336)
    at org.eclipse.core.launcher.Main.basicRun(Main.java:280)
    at org.eclipse.core.launcher.Main.run(Main.java:977)
    at org.eclipse.core.launcher.Main.main(Main.java:952)&quot;

**Comment by anb0s** [comment]
Comment by gbrocker on Tue Apr 03 17:30:22 2007

The bug occured in all eclipse version.

**Comment by anb0s** [comment]
Closed by gbrocker on Wed Apr 04 10:13:34 2007

**Comment by anb0s** [comment]
Comment by gbrocker on Wed Apr 04 10:13:34 2007

A new eclox release that fixes this bug is now published on the update site (http://download.gna.org/eclox/update) and as a stand-alone package (http://download.gna.org/eclox/packages/eclox_0.6.2.zip).

Thank you for your contribution.

Guillaume
