### ISSUE TITLE
Eclipse 3.2.2 (M20070212-1330) Can not create Doxyfile.

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#66]
Original Savannah ticket 8976 reported by gbrocker on Fri Apr 20 16:14:33 2007.

java version &quot;1.6.0&quot;
Java(TM) SE Runtime Environment (build 1.6.0-b105)
Java HotSpot(TM) Client VM (build 1.6.0-b105, mixed mode, sharing)

Eclipse 3.2.2 (M20070212-1330) 

Eclipse C/C++ Development Tools
Version: 3.1.2.200702150621
Build id: 200702150621

Here is the log:

!ENTRY org.eclipse.jface 4 2 2007-04-20 10:11:44.501
!MESSAGE Problems occurred when invoking code from plug-in: &quot;org.eclipse.jface&quot;.
!STACK 0
java.lang.ClassCastException: org.eclipse.cdt.internal.core.model.CProject cannot be cast to org.eclipse.core.resources.IResource
        at eclox.ui.wizard.NewDoxyfileWizardPage.&lt;init&gt;(NewDoxyfileWizardPage.java:55)
        at eclox.ui.wizard.NewDoxyfileWizard.init(NewDoxyfileWizard.java:54)
        at org.eclipse.ui.internal.dialogs.WorkbenchWizardNode.getWizard(WorkbenchWizardNode.java:173)
        at org.eclipse.jface.wizard.WizardSelectionPage.getNextPage(WizardSelectionPage.java:104)
        at org.eclipse.ui.internal.dialogs.WorkbenchWizardSelectionPage.getNextPage(WorkbenchWizardSelectionPage.java:100)
        at org.eclipse.ui.internal.dialogs.NewWizardSelectionPage.advanceToNextPageOrFinish(NewWizardSelectionPage.java:71)
        at org.eclipse.ui.internal.dialogs.NewWizardNewPage$1.doubleClick(NewWizardNewPage.java:355)
        at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:796)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
        at org.eclipse.core.runtime.Platform.run(Platform.java:843)
        at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:149)
        at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:794)
        at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1227)
        at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1158)
        at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:223)
        at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:220)
        at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:281)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3180)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2856)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:820)
        at org.eclipse.jface.window.Window.open(Window.java:796)
        at org.eclipse.ui.actions.NewWizardAction.run(NewWizardAction.java:181)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:539)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:488)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:400)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3180)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2856)
        at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:1930)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:1894)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:422)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
        at org.eclipse.ui.internal.ide.IDEApplication.run(IDEApplication.java:95)
        at org.eclipse.core.internal.runtime.PlatformActivator$1.run(PlatformActivator.java:78)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:92)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:68)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:177)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.core.launcher.Main.invokeFramework(Main.java:336)
        at org.eclipse.core.launcher.Main.basicRun(Main.java:280)
        at org.eclipse.core.launcher.Main.run(Main.java:977)
        at org.eclipse.core.launcher.Main.main(Main.java:952)

**Comment by anb0s** [comment]
Comment by None on Fri Apr 20 16:18:15 2007

Doxygen version 1.5.2
Copyright Dimitri van Heesch 1997-2007

**Comment by anb0s** [comment]
Comment by None on Fri Apr 20 16:21:31 2007

This have also encountered this problem on Windows and Linux. This error occurs whenever I try to create a new doxyfile. If a valid doxyfile already exists the eclox UI seems to work.

**Comment by anb0s** [comment]
Comment by gbrocker on Mon Apr 23 14:31:46 2007

The selection was expected to have the IResource interface.

Now, when no IResource interface is found for the current selection, eclox tries to find an adapter to get it.

Thank you for your submission and stay tuned for the upcoming release (0.6.3) that will include the fix.

Guillaume

**Comment by anb0s** [comment]
Closed by gbrocker on Fri Jun 22 15:09:03 2007
