### ISSUE TITLE
crash under eclipse 3.2

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#72]
Original Savannah ticket 9943 reported by gbrocker on Thu Sep 06 01:11:14 2007.

i get the following exception when trying to edit doxyfile under eclipse 3.2:

java.lang.NullPointerException
    at eclox.ui.editor.editors.TextEditor.setInput(TextEditor.java:172)
    at eclox.ui.editor.basic.ProjectPart.&lt;init&gt;(ProjectPart.java:82)
    at eclox.ui.editor.basic.Page.createFormContent(Page.java:72)
    at org.eclipse.ui.forms.editor.FormPage$1.run(FormPage.java:151)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
    at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:149)
    at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:462)
    at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:596)
    at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:280)
    at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:596)
    at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:372)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:566)
    at org.eclipse.ui.internal.EditorReference.getEditor(EditorReference.java:214)
    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditorBatched(WorkbenchPage.java:2588)
    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:2521)
    at org.eclipse.ui.internal.WorkbenchPage.access$10(WorkbenchPage.java:2513)
    at org.eclipse.ui.internal.WorkbenchPage$9.run(WorkbenchPage.java:2498)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2493)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2478)
    at org.eclipse.ui.ide.IDE.openEditor(IDE.java:388)
    at org.eclipse.ui.ide.IDE.openEditor(IDE.java:350)
    at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:275)
    at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:139)
    at org.eclipse.jdt.internal.ui.actions.OpenActionUtil.open(OpenActionUtil.java:49)
    at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:190)
    at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:174)
    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:267)
    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:243)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerActionGroup.handleOpen(PackageExplorerActionGroup.java:306)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart$4.open(PackageExplorerPart.java:651)
    at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:817)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
    at org.eclipse.core.runtime.Platform.run(Platform.java:843)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:44)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:149)
    at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:815)
    at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1069)
    at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1168)
    at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:249)
    at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:243)
    at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:283)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:928)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3348)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2968)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:1914)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:1878)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:419)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.IDEApplication.run(IDEApplication.java:95)
    at org.eclipse.core.internal.runtime.PlatformActivator$1.run(PlatformActivator.java:78)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:92)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:68)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.core.launcher.Main.invokeFramework(Main.java:336)
    at org.eclipse.core.launcher.Main.basicRun(Main.java:280)
    at org.eclipse.core.launcher.Main.run(Main.java:977)
    at org.eclipse.core.launcher.Main.main(Main.java:952)

**Comment by anb0s** [comment]
Comment by gbrocker on Thu Sep 06 09:42:13 2007

Hi!

Could you please, give more details about what you done to find this bug out ? I think about the doxyfile you were editing, which setting, and so on...

Thanks.

Guillaume

**Comment by anb0s** [comment]
Comment by None on Thu Sep 06 17:46:53 2007

Hello Guillaume,

I am somewhat of an eclipse newbie, I just added a new empty doxyfile and double clicked on it; could it be some interaction with some other plugins i use? I was using the java perspective.

regards

alessandro

**Comment by anb0s** [comment]
Comment by gbrocker on Fri Sep 07 09:53:08 2007

If the doxyfile that caused the crash is still available, could you attach it to this tracker ? I hope this will help me to find out the cause of the bug.

Thanks.

Guillaume

**Comment by anb0s** [comment]
Closed by gbrocker on Mon Apr 21 17:00:02 2008

**Comment by anb0s** [comment]
Comment by gbrocker on Mon Apr 21 17:00:03 2008

See this bug is likely to the same as bug #9456.
